name: CI
on: [push, pull_request]
jobs:

  testing:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
      run: |
        go version
        go env

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Use cache for go module directory
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check Go modules and vendoring
      run: |
        go mod tidy -v
        go mod download

    - name: Install test dependencies
      run: make install-test

    - name: Check the code
      run: make lint

    - name: Run tests
      run: make test

    - name: Git changes
      run: |
        echo "check if linters resulted in any changes:"
        git status --porcelain
        test -z "$(git status --porcelain)"
